# Site Settings
title: Start Jekyll
email: nnvdprasad@gmail.com
description: >
  A guide to getting started with Jekyll.
baseurl: "/mms"
url: "https://nnvdprasad.github.io"
twitter_username: nnvdprasad
github_username:  nnvdprasad
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM